export const CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "San Francisco",
  "Indianapolis",
  "Columbus",
  "Fort Worth",
  "Charlotte",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Detroit",
  "Nashville",
  "Portland",
  "Memphis",
  "Oklahoma City",
  "Las Vegas",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Long Beach",
  "Omaha",
  "Raleigh",
  "Miami",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Cleveland",
  "Wichita",
  "Arlington",
  "New Orleans",
  "Bakersfield",
  "Tampa",
  "Honolulu",
  "Anaheim",
  "Aurora",
  "Santa Ana",
  "Corpus Christi",
  "Riverside",
  "St. Louis",
  "Lexington",
  "Stockton",
  "Pittsburgh",
  "Saint Paul",
  "Anchorage",
  "Cincinnati",
  "Henderson",
  "Greensboro",
  "Plano",
  "Newark",
  "Toledo",
  "Lincoln",
  "Orlando",
  "Chula Vista",
  "Jersey City",
  "Chandler",
  "Fort Wayne",
  "Buffalo",
  "Durham",
  "St. Petersburg",
  "Irvine",
  "Laredo",
  "Lubbock",
  "Madison",
  "Gilbert",
  "Norfolk",
  "Reno",
  "Winston-Salem",
  "Glendale",
  "Hialeah",
  "Garland",
  "Scottsdale",
  "Irving",
  "Chesapeake",
  "North Las Vegas",
  "Fremont",
  "Baton Rouge",
  "Richmond",
  "Boise",
  "San Bernardino",
  "Spokane",
  "Des Moines",
  "Tacoma",
  "Modesto",
  "Fontana",
  "Santa Clarita",
  "Birmingham",
  "Oxnard",
  "Fayetteville",
  "Moreno Valley",
  "Rochester",
  "Glendale",
  "Huntington Beach",
  "Salt Lake City",
  "Grand Rapids",
  "Amarillo",
  "Yonkers",
  "Aurora",
  "Montgomery",
  "Akron",
  "Little Rock",
  "Huntsville",
  "Augusta",
  "Port St. Lucie",
  "Grand Prairie",
  "Columbus",
  "Tallahassee",
  "Overland Park",
  "Tempe",
  "McKinney",
  "Mobile",
  "Cape Coral",
  "Shreveport",
  "Frisco",
  "Knoxville",
  "Worcester",
  "Brownsville",
  "Vancouver",
  "Fort Lauderdale",
  "Sioux Falls",
  "Ontario",
  "Chattanooga",
  "Providence",
  "Newport News",
  "Rancho Cucamonga",
  "Santa Rosa",
  "Oceanside",
  "Salem",
  "Elk Grove",
  "Garden Grove",
  "Pembroke Pines",
  "Peoria",
  "Eugene",
  "Corona",
  "Cary",
  "Springfield",
  "Fort Collins",
  "Jackson",
  "Alexandria",
  "Hayward",
  "Lancaster",
  "Lakewood",
  "Clarksville",
  "Palmdale",
  "Salinas",
  "Springfield",
  "Hollywood",
  "Pasadena",
  "Sunnyvale",
  "Macon",
  "Kansas City",
  "Pomona",
  "Escondido",
  "Killeen",
  "Naperville",
  "Joliet",
  "Bellevue",
  "Rockford",
  "Savannah",
  "Paterson",
  "Torrance",
  "Bridgeport",
  "Mesquite",
  "Orange",
  "Fullerton",
  "Miramar",
  "Thornton",
  "Roseville",
  "Denton",
  "Waco",
  "Surprise",
  "Carrollton",
  "West Valley City",
  "Charleston",
  "Warren",
  "Hampton",
  "Gainesville",
  "Visalia",
  "Coral Springs",
  "Columbia",
  "Cedar Rapids",
  "Sterling Heights",
  "New Haven",
  "Stamford",
  "Concord",
  "Kent",
  "Santa Clara",
  "Elizabeth",
  "Round Rock",
  "Thousand Oaks",
  "Lafayette",
  "Athens",
  "Topeka",
  "Simi Valley",
  "Fargo",
  "Norman",
  "Columbia",
  "Abilene",
  "Wilmington",
  "Hartford",
  "Victorville",
  "Pearland",
  "Vallejo",
  "Ann Arbor",
  "Berkeley",
  "Allentown",
  "Richardson",
  "Odessa",
  "Arvada",
  "Cambridge",
  "Sugar Land",
  "Beaumont",
  "Lansing",
  "Evansville",
  "Rochester",
  "Independence",
  "Fairfield",
  "Provo",
  "Clearwater",
  "Carlsbad",
  "Westminster",
  "West Jordan",
  "Murrieta",
  "Downey",
  "Gresham",
  "Waterbury",
  "Costa Mesa",
  "Inglewood",
  "Manchester",
  "Lowell",
  "Wilmington",
  "Richmond",
  "Fargo",
  "Arden-Arcade",
  "Ventura",
  "Pueblo",
  "West Covina",
  "Boulder",
  "Norwalk",
  "Daly City",
  "Burbank",
  "Green Bay",
  "Santa Maria",
  "Wichita Falls",
  "El Cajon",
  "Rialto",
  "Las Cruces",
  "San Mateo",
  "Edison",
  "Davenport",
  "Hillsboro",
  "Woodbridge",
  "Lawton",
  "South Bend",
  "Vista",
  "Greeley",
  "Davie",
  "San Angelo",
  "Jurupa Valley",
  "Renton",
  "Roanoke",
  "Kenosha",
  "Napa",
  "Scottsdale",
  "Avondale",
  "Somerville",
  "Louisville",
  "Farmington Hills",
  "Santa Monica",
  "Whittier",
  "Bend",
  "Livonia",
  "Miami Beach",
  "Elgin",
  "Daly City",
  "Pompano Beach",
  "Apple Valley",
  "Clifton",
  "Redding",
  "Turlock",
  "Nampa",
  "Allen",
  "St. Joseph",
  "Bristol",
  "Concord",
  "Sandy Springs",
  "Hoover",
  "Hemet",
  "Albany",
  "Rio Rancho",
  "Bloomington",
  "St. George",
  "Bolingbrook",
  "Flower Mound",
  "New Braunfels",
  "Cicero",
  "Port Arthur",
  "Missouri City",
  "North Charleston",
  "Euless",
  "North Port",
  "Norfolk",
  "Frisco",
  "Lauderhill",
  "Pocatello",
  "Palm Coast",
  "Ceres",
  "Sanford",
  "Elmhurst",
  "Rock Hill",
  "Lehigh Acres",
  "Saginaw",
  "Bountiful",
  "Waukesha",
  "San Marcos",
  "Normal",
  "Rowlett",
  "Tustin",
  "Mount Pleasant",
  "Elkhart",
  "Kannapolis",
  "Hanford",
  "Greenwood",
  "Coconut Creek",
  "Wheaton",
  "Blue Springs",
  "Colton",
  "Port Orange",
  "Ocala",
  "Cheyenne",
  "Summerville",
  "Casa Grande",
  "Malden",
  "Lake Charles",
  "Lenexa",
  "DeSoto",
  "Texarkana",
  "Burien",
  "Lacey",
  "Union City",
  "Mount Vernon",
  "Edina",
  "Lakewood",
  "Auburn",
  "Meridian",
  "St. Cloud",
  "Homestead",
  "Tamarac",
  "Columbia",
  "Waterloo",
  "Brentwood",
  "Springdale",
  "Novato",
  "Taylor",
  "Cicero",
  "Yuba City",
  "Prescott",
  "Fort Myers",
  "Delray Beach",
  "Rancho Cordova",
  "Eagan",
  "Shawnee",
  "Santa Cruz",
  "Lodi",
  "Middletown",
  "Southaven",
  "Canton",
  "Marysville",
  "Pearland",
  "Grand Forks",
  "Palm Desert",
  "Orland Park",
  "Huntington Park",
  "Taunton",
  "Rocky Mount",
  "Aliso Viejo",
  "Tinley Park",
  "Diamond Bar",
  "Caldwell",
  "Conroe",
  "Montebello",
  "Hendersonville",
  "Moline",
  "Biloxi",
  "Laguna Niguel",
  "Pensacola",
  "La Mesa",
  "Fountain Valley",
  "Camden",
  "West Allis",
  "Tigard",
  "El Centro",
  "Revere",
  "Lancaster",
  "Poway",
  "Altoona",
  "Montgomery Village",
  "Gulfport",
  "Fitchburg",
  "Apple Valley",
  "Wauwatosa",
  "Bowie",
  "Burlington",
  "Attleboro",
  "Olympia",
  "La Crosse",
  "North Little Rock",
  "Eastvale",
  "Strongsville",
  "North Miami Beach",
  "Laguna Niguel",
  "Columbus",
  "Littleton",
  "West Sacramento",
  "Rock Hill",
  "Prescott Valley",
  "Elyria",
  "Minnetonka",
  "Coachella",
  "Muskogee",
  "Cerritos",
  "Palm Springs",
  "Beavercreek",
  "New Brunswick",
  "Oak Lawn",
  "Bradenton",
  "Gilroy",
  "Richland",
  "San Rafael",
  "Grand Island",
  "National City",
  "Peabody",
  "Georgetown",
  "Stanton",
  "Rogers",
  "Hurst",
  "Poway",
  "Brea",
  "Morgan Hill",
  "Campbell",
  "Covina",
  "Beaumont",
  "Cypress",
  "Levittown",
  "Azusa",
  "Euclid",
  "Castle Rock",
  "Rosemead",
  "Bonita Springs",
  "Apex",
  "Crystal Lake",
  "Hattiesburg",
  "Hutchinson",
  "Puyallup",
  "Middletown",
  "Huntington",
  "La Quinta",
  "Aliso Viejo",
  "Maricopa",
  "Sammamish",
  "Coon Rapids",
  "Orland Park",
  "Lakeville",
  "Hagerstown",
  "Chino Hills",
  "Dunwoody",
  "Hickory",
  "St. Clair Shores",
  "Florence",
  "Newark",
  "Rapid City",
  "Victoria",
  "Oak Park",
  "Apex",
  "New Berlin",
  "Winter Garden",
  "Brookhaven",
  "Bowie",
  "Novi",
  "Elkhart",
  "Riverton",
  "Concord",
  "Kokomo",
  "Moline",
  "Roseville",
  "Barnstable Town",
  "Jefferson City",
  "Roswell",
  "Missoula",
  "Rockville",
  "Rockwall",
  "Medford",
  "Midland",
  "Stillwater",
  "Bayonne",
  "Parker",
  "Bedford",
  "York",
  "Burleson",
  "Salem",
  "East Providence",
  "West New York",
  "Goodyear",
  "Sheboygan",
  "Mankato",
  "Galveston",
  "Lakewood",
  "Grapevine",
  "Waltham",
  "Mount Prospect",
  "Chicopee",
  "Twin Falls",
  "Edmonds",
  "East Lansing",
  "Muskogee",
  "Belleville",
  "Cleveland",
  "Leominster",
  "Milford",
  "Cuyahoga Falls",
  "Manhattan",
  "Manhattan",
  "Bay City",
  "Sayreville",
  "Haltom City",
  "Burien",
  "Wylie",
  "Franklin",
  "Bartlett",
  "Coral Gables",
  "Montclair",
  "St. Charles",
  "Santee",
  "Woburn",
  "Watsonville",
  "Baytown",
  "Bountiful",
  "Attleboro",
  "Huntsville",
  "Lake Elsinore",
  "Dunedin",
  "Beverly",
  "Moline",
  "Morgan Hill",
  "Santa Fe",
  "Highland",
  "Lebanon",
  "Coachella",
  "Manassas",
  "Pleasant Grove",
  "Seaside",
  "Delaware",
  "Spring Hill",
  "Palm Beach Gardens",
  "Lake Oswego",
  "Woodland",
  "Newark",
  "Everett",
  "Collierville",
  "Westfield",
  "Fairfield",
  "Commerce City",
  "Apopka",
  "Newberg",
  "Columbus",
  "Ocoee",
  "Edina",
  "North Lauderdale",
  "Levittown",
  "Cupertino",
  "Hanover Park",
  "Muskegon",
  "DeKalb",
  "Burlington",
  "Ceres",
  "Prescott",
  "Woodland",
  "Palm Bay",
  "Rocklin",
  "Norwich",
  "Cape Girardeau",
  "La Mirada",
  "La Puente",
  "Elmira",
  "Valley Stream",
  "Casa Grande",
  "Lacey",
  "Columbus",
  "Pittsfield",
  "Cedar Hill",
  "Manhattan",
  "Coral Terrace",
  "East Providence",
  "Grove City",
  "Leesburg",
  "Troy",
  "Kingsport",
  "Lake Havasu City",
  "Charlottesville",
  "Hackensack",
  "Beverly",
  "Blacksburg",
  "Bullhead City",
  "Columbus",
  "Harrisonburg",
  "Lompoc",
  "Woburn",
  "Kearny",
  "Cleveland Heights",
  "Glenview",
  "Greenwood",
  "Coconut Creek",
  "Wilson",
  "Cleveland",
  "Mansfield",
  "Southaven",
  "Bentonville",
  "Hilton Head Island",
  "Kannapolis",
  "Kirkland",
  "Levittown",
  "Watertown",
  "Wyoming",
  "Schenectady",
  "Richmond",
  "North Miami",
  "Farmington",
  "Glenview",
  "Caldwell",
  "Yorba Linda",
  "Westland",
  "Redmond",
  "DeSoto",
  "Carmel",
  "Haverhill",
  "Mansfield",
  "Brea",
  "Blacksburg",
  "Portsmouth",
  "Richmond",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
  "Haverhill",
  "Edmonds",
  "Richland",
  "Broomfield",
  "Muskogee",
  "Wylie",
  "Minnetonka",
  "Crystal Lake",
  "Broomfield",
  "Kannapolis",
];
