export const COUNTRIES = [
  { id: 1, name: "Afghanistan", code: "AF", codeNumber: "+93" },
  { id: 2, name: "Åland Islands", code: "AX", codeNumber: "+358" },
  { id: 3, name: "Albania", code: "AL", codeNumber: "+355" },
  { id: 4, name: "Algeria", code: "DZ", codeNumber: "+213" },
  { id: 5, name: "American Samoa", code: "AS", codeNumber: "+1" },
  { id: 6, name: "Andorra", code: "AD", codeNumber: "+376" },
  { id: 7, name: "Angola", code: "AO", codeNumber: "+244" },
  { id: 8, name: "Anguilla", code: "AI", codeNumber: "+1" },
  { id: 9, name: "Antarctica", code: "AQ", codeNumber: "+672" },
  { id: 10, name: "Antigua and Barbuda", code: "AG", codeNumber: "+1" },
  { id: 11, name: "Argentina", code: "AR", codeNumber: "+54" },
  { id: 12, name: "Armenia", code: "AM", codeNumber: "+374" },
  { id: 13, name: "Aruba", code: "AW", codeNumber: "+297" },
  { id: 14, name: "Australia", code: "AU", codeNumber: "+61" },
  { id: 15, name: "Austria", code: "AT", codeNumber: "+43" },
  { id: 16, name: "Azerbaijan", code: "AZ", codeNumber: "+994" },
  { id: 17, name: "Bahamas", code: "BS", codeNumber: "+1" },
  { id: 18, name: "Bahrain", code: "BH", codeNumber: "+973" },
  { id: 19, name: "Bangladesh", code: "BD", codeNumber: "+880" },
  { id: 20, name: "Barbados", code: "BB", codeNumber: "+1" },
  { id: 21, name: "Belarus", code: "BY", codeNumber: "+375" },
  { id: 22, name: "Belgium", code: "BE", codeNumber: "+32" },
  { id: 23, name: "Belize", code: "BZ", codeNumber: "+501" },
  { id: 24, name: "Benin", code: "BJ", codeNumber: "+229" },
  { id: 25, name: "Bermuda", code: "BM", codeNumber: "+1" },
  { id: 26, name: "Bhutan", code: "BT", codeNumber: "+975" },
  {
    id: 27,
    name: "Bolivia (Plurinational State of)",
    code: "BO",
    codeNumber: "+591",
  },
  {
    id: 28,
    name: "Bonaire, Sint Eustatius and Saba",
    code: "BQ",
    codeNumber: "+599",
  },
  { id: 29, name: "Bosnia and Herzegovina", code: "BA", codeNumber: "+387" },
  { id: 30, name: "Botswana", code: "BW", codeNumber: "+267" },
  { id: 31, name: "Bouvet Island", code: "BV", codeNumber: "" },
  { id: 32, name: "Brazil", code: "BR", codeNumber: "+55" },
  {
    id: 33,
    name: "British Indian Ocean Territory",
    code: "IO",
    codeNumber: "+246",
  },
  { id: 34, name: "Brunei Darussalam", code: "BN", codeNumber: "+673" },
  { id: 35, name: "Bulgaria", code: "BG", codeNumber: "+359" },
  { id: 36, name: "Burkina Faso", code: "BF", codeNumber: "+226" },
  { id: 37, name: "Burundi", code: "BI", codeNumber: "+257" },
  { id: 38, name: "Cabo Verde", code: "CV", codeNumber: "+238" },
  { id: 39, name: "Cambodia", code: "KH", codeNumber: "+855" },
  { id: 40, name: "Cameroon", code: "CM", codeNumber: "+237" },
  { id: 41, name: "Canada", code: "CA", codeNumber: "+1" },
  { id: 42, name: "Cayman Islands", code: "KY", codeNumber: "+1" },
  { id: 43, name: "Central African Republic", code: "CF", codeNumber: "+236" },
  { id: 44, name: "Chad", code: "TD", codeNumber: "+235" },
  { id: 45, name: "Chile", code: "CL", codeNumber: "+56" },
  { id: 46, name: "China", code: "CN", codeNumber: "+86" },
  { id: 47, name: "Christmas Island", code: "CX", codeNumber: "+61" },
  { id: 48, name: "Cocos (Keeling) Islands", code: "CC", codeNumber: "+61" },
  { id: 49, name: "Colombia", code: "CO", codeNumber: "+57" },
  { id: 50, name: "Comoros", code: "KM", codeNumber: "+269" },
  { id: 51, name: "Congo", code: "CG", codeNumber: "+242" },
  {
    id: 52,
    name: "Congo (Democratic Republic of the)",
    code: "CD",
    codeNumber: "+243",
  },
  { id: 53, name: "Cook Islands", code: "CK", codeNumber: "+682" },
  { id: 54, name: "Costa Rica", code: "CR", codeNumber: "+506" },
  { id: 55, name: "Croatia", code: "HR", codeNumber: "+385" },
  { id: 56, name: "Cuba", code: "CU", codeNumber: "+53" },
  { id: 57, name: "Curaçao", code: "CW", codeNumber: "+599" },
  { id: 58, name: "Cyprus", code: "CY", codeNumber: "+357" },
  { id: 59, name: "Czech Republic", code: "CZ", codeNumber: "+420" },
  { id: 60, name: "Denmark", code: "DK", codeNumber: "+45" },
  { id: 61, name: "Djibouti", code: "DJ", codeNumber: "+253" },
  { id: 62, name: "Dominica", code: "DM", codeNumber: "+1" },
  { id: 63, name: "Dominican Republic", code: "DO", codeNumber: "+1" },
  { id: 64, name: "Ecuador", code: "EC", codeNumber: "+593" },
  { id: 65, name: "Egypt", code: "EG", codeNumber: "+20" },
  { id: 66, name: "El Salvador", code: "SV", codeNumber: "+503" },
  { id: 67, name: "Equatorial Guinea", code: "GQ", codeNumber: "+240" },
  { id: 68, name: "Eritrea", code: "ER", codeNumber: "+291" },
  { id: 69, name: "Estonia", code: "EE", codeNumber: "+372" },
  { id: 70, name: "Ethiopia", code: "ET", codeNumber: "+251" },
  {
    id: 71,
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    codeNumber: "+500",
  },
  { id: 72, name: "Faroe Islands", code: "FO", codeNumber: "+298" },
  { id: 73, name: "Fiji", code: "FJ", codeNumber: "+679" },
  { id: 74, name: "Finland", code: "FI", codeNumber: "+358" },
  { id: 75, name: "France", code: "FR", codeNumber: "+33" },
  { id: 76, name: "French Guiana", code: "GF", codeNumber: "+594" },
  { id: 77, name: "French Polynesia", code: "PF", codeNumber: "+689" },
  { id: 78, name: "French Southern Territories", code: "TF", codeNumber: "" },
  { id: 79, name: "Gabon", code: "GA", codeNumber: "+241" },
  { id: 80, name: "Gambia", code: "GM", codeNumber: "+220" },
  { id: 81, name: "Georgia", code: "GE", codeNumber: "+995" },
  { id: 82, name: "Germany", code: "DE", codeNumber: "+49" },
  { id: 83, name: "Ghana", code: "GH", codeNumber: "+233" },
  { id: 84, name: "Gibraltar", code: "GI", codeNumber: "+350" },
  { id: 85, name: "Greece", code: "GR", codeNumber: "+30" },
  { id: 86, name: "Greenland", code: "GL", codeNumber: "+299" },
  { id: 87, name: "Grenada", code: "GD", codeNumber: "+1" },
  { id: 88, name: "Guadeloupe", code: "GP", codeNumber: "+590" },
  { id: 89, name: "Guam", code: "GU", codeNumber: "+1" },
  { id: 90, name: "Guatemala", code: "GT", codeNumber: "+502" },
  { id: 91, name: "Guernsey", code: "GG", codeNumber: "+44" },
  { id: 92, name: "Guinea", code: "GN", codeNumber: "+224" },
  { id: 93, name: "Guinea-Bissau", code: "GW", codeNumber: "+245" },
  { id: 94, name: "Guyana", code: "GY", codeNumber: "+592" },
  { id: 95, name: "Haiti", code: "HT", codeNumber: "+509" },
  {
    id: 96,
    name: "Heard Island and McDonald Islands",
    code: "HM",
    codeNumber: "",
  },
  { id: 97, name: "Holy See", code: "VA", codeNumber: "+379" },
  { id: 98, name: "Honduras", code: "HN", codeNumber: "+504" },
  { id: 99, name: "Hong Kong", code: "HK", codeNumber: "+852" },
  { id: 100, name: "Hungary", code: "HU", codeNumber: "+36" },
  { id: 101, name: "Iceland", code: "IS", codeNumber: "+354" },
  { id: 102, name: "India", code: "IN", codeNumber: "+91" },
  { id: 103, name: "Indonesia", code: "ID", codeNumber: "+62" },
  {
    id: 104,
    name: "Iran (Islamic Republic of)",
    code: "IR",
    codeNumber: "+98",
  },
  { id: 105, name: "Iraq", code: "IQ", codeNumber: "+964" },
  { id: 106, name: "Ireland", code: "IE", codeNumber: "+353" },
  { id: 107, name: "Isle of Man", code: "IM", codeNumber: "+44" },
  { id: 108, name: "Israel", code: "IL", codeNumber: "+972" },
  { id: 109, name: "Italy", code: "IT", codeNumber: "+39" },
  { id: 110, name: "Jamaica", code: "JM", codeNumber: "+1" },
  { id: 111, name: "Japan", code: "JP", codeNumber: "+81" },
  { id: 112, name: "Jersey", code: "JE", codeNumber: "+44" },
  { id: 113, name: "Jordan", code: "JO", codeNumber: "+962" },
  { id: 114, name: "Kazakhstan", code: "KZ", codeNumber: "+7" },
  { id: 115, name: "Kenya", code: "KE", codeNumber: "+254" },
  { id: 116, name: "Kiribati", code: "KI", codeNumber: "+686" },
  {
    id: 117,
    name: "Korea (Democratic People's Republic of)",
    code: "KP",
    codeNumber: "+850",
  },
  { id: 118, name: "Korea (Republic of)", code: "KR", codeNumber: "+82" },
  { id: 119, name: "Kuwait", code: "KW", codeNumber: "+965" },
  { id: 120, name: "Kyrgyzstan", code: "KG", codeNumber: "+996" },
  {
    id: 121,
    name: "Lao People's Democratic Republic",
    code: "LA",
    codeNumber: "+856",
  },
  { id: 122, name: "Latvia", code: "LV", codeNumber: "+371" },
  { id: 123, name: "Lebanon", code: "LB", codeNumber: "+961" },
  { id: 124, name: "Lesotho", code: "LS", codeNumber: "+266" },
  { id: 125, name: "Liberia", code: "LR", codeNumber: "+231" },
  { id: 126, name: "Libya", code: "LY", codeNumber: "+218" },
  { id: 127, name: "Liechtenstein", code: "LI", codeNumber: "+423" },
  { id: 128, name: "Lithuania", code: "LT", codeNumber: "+370" },
  { id: 129, name: "Luxembourg", code: "LU", codeNumber: "+352" },
  { id: 130, name: "Macao", code: "MO", codeNumber: "+853" },
  {
    id: 131,
    name: "Macedonia (the former Yugoslav Republic of)",
    code: "MK",
    codeNumber: "+389",
  },
  { id: 132, name: "Madagascar", code: "MG", codeNumber: "+261" },
  { id: 133, name: "Malawi", code: "MW", codeNumber: "+265" },
  { id: 134, name: "Malaysia", code: "MY", codeNumber: "+60" },
  { id: 135, name: "Maldives", code: "MV", codeNumber: "+960" },
  { id: 136, name: "Mali", code: "ML", codeNumber: "+223" },
  { id: 137, name: "Malta", code: "MT", codeNumber: "+356" },
  { id: 138, name: "Marshall Islands", code: "MH", codeNumber: "+692" },
  { id: 139, name: "Martinique", code: "MQ", codeNumber: "+596" },
  { id: 140, name: "Mauritania", code: "MR", codeNumber: "+222" },
  { id: 141, name: "Mauritius", code: "MU", codeNumber: "+230" },
  { id: 142, name: "Mayotte", code: "YT", codeNumber: "+262" },
  { id: 143, name: "Mexico", code: "MX", codeNumber: "+52" },
  {
    id: 144,
    name: "Micronesia (Federated States of)",
    code: "FM",
    codeNumber: "+691",
  },
  { id: 145, name: "Moldova (Republic of)", code: "MD", codeNumber: "+373" },
  { id: 146, name: "Monaco", code: "MC", codeNumber: "+377" },
  { id: 147, name: "Mongolia", code: "MN", codeNumber: "+976" },
  { id: 148, name: "Montenegro", code: "ME", codeNumber: "+382" },
  { id: 149, name: "Montserrat", code: "MS", codeNumber: "+1" },
  { id: 150, name: "Morocco", code: "MA", codeNumber: "+212" },
  { id: 151, name: "Mozambique", code: "MZ", codeNumber: "+258" },
  { id: 152, name: "Myanmar", code: "MM", codeNumber: "+95" },
  { id: 153, name: "Namibia", code: "NA", codeNumber: "+264" },
  { id: 154, name: "Nauru", code: "NR", codeNumber: "+674" },
  { id: 155, name: "Nepal", code: "NP", codeNumber: "+977" },
  { id: 156, name: "Netherlands", code: "NL", codeNumber: "+31" },
  { id: 157, name: "New Caledonia", code: "NC", codeNumber: "+687" },
  { id: 158, name: "New Zealand", code: "NZ", codeNumber: "+64" },
  { id: 159, name: "Nicaragua", code: "NI", codeNumber: "+505" },
  { id: 160, name: "Niger", code: "NE", codeNumber: "+227" },
  { id: 161, name: "Nigeria", code: "NG", codeNumber: "+234" },
  { id: 162, name: "Niue", code: "NU", codeNumber: "+683" },
  { id: 163, name: "Norfolk Island", code: "NF", codeNumber: "+672" },
  { id: 164, name: "Northern Mariana Islands", code: "MP", codeNumber: "+1" },
  { id: 165, name: "Norway", code: "NO", codeNumber: "+47" },
  { id: 166, name: "Oman", code: "OM", codeNumber: "+968" },
  { id: 167, name: "Pakistan", code: "PK", codeNumber: "+92" },
  { id: 168, name: "Palau", code: "PW", codeNumber: "+680" },
  { id: 169, name: "Palestine, State of", code: "PS", codeNumber: "+970" },
  { id: 170, name: "Panama", code: "PA", codeNumber: "+507" },
  { id: 171, name: "Papua New Guinea", code: "PG", codeNumber: "+675" },
  { id: 172, name: "Paraguay", code: "PY", codeNumber: "+595" },
  { id: 173, name: "Peru", code: "PE", codeNumber: "+51" },
  { id: 174, name: "Philippines", code: "PH", codeNumber: "+63" },
  { id: 175, name: "Pitcairn", code: "PN", codeNumber: "+870" },
  { id: 176, name: "Poland", code: "PL", codeNumber: "+48" },
  { id: 177, name: "Portugal", code: "PT", codeNumber: "+351" },
  { id: 178, name: "Puerto Rico", code: "PR", codeNumber: "+1" },
  { id: 179, name: "Qatar", code: "QA", codeNumber: "+974" },
  { id: 180, name: "Réunion", code: "RE", codeNumber: "+262" },
  { id: 181, name: "Romania", code: "RO", codeNumber: "+40" },
  { id: 182, name: "Russian Federation", code: "RU", codeNumber: "+7" },
  { id: 183, name: "Rwanda", code: "RW", codeNumber: "+250" },
  { id: 184, name: "Saint Barthélemy", code: "BL", codeNumber: "+590" },
  {
    id: 185,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    codeNumber: "+290",
  },
  { id: 186, name: "Saint Kitts and Nevis", code: "KN", codeNumber: "+1" },
  { id: 187, name: "Saint Lucia", code: "LC", codeNumber: "+1" },
  {
    id: 188,
    name: "Saint Martin (French part)",
    code: "MF",
    codeNumber: "+590",
  },
  {
    id: 189,
    name: "Saint Pierre and Miquelon",
    code: "PM",
    codeNumber: "+508",
  },
  {
    id: 190,
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    codeNumber: "+1",
  },
  { id: 191, name: "Samoa", code: "WS", codeNumber: "+685" },
  { id: 192, name: "San Marino", code: "SM", codeNumber: "+378" },
  { id: 193, name: "Sao Tome and Principe", code: "ST", codeNumber: "+239" },
  { id: 194, name: "Saudi Arabia", code: "SA", codeNumber: "+966" },
  { id: 195, name: "Senegal", code: "SN", codeNumber: "+221" },
  { id: 196, name: "Serbia", code: "RS", codeNumber: "+381" },
  { id: 197, name: "Seychelles", code: "SC", codeNumber: "+248" },
  { id: 198, name: "Sierra Leone", code: "SL", codeNumber: "+232" },
  { id: 199, name: "Singapore", code: "SG", codeNumber: "+65" },
  { id: 200, name: "Sint Maarten (Dutch part)", code: "SX", codeNumber: "+1" },
  { id: 201, name: "Slovakia", code: "SK", codeNumber: "+421" },
  { id: 202, name: "Slovenia", code: "SI", codeNumber: "+386" },
  { id: 203, name: "Solomon Islands", code: "SB", codeNumber: "+677" },
  { id: 204, name: "Somalia", code: "SO", codeNumber: "+252" },
  { id: 205, name: "South Africa", code: "ZA", codeNumber: "+27" },
  {
    id: 206,
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    codeNumber: "",
  },
  { id: 207, name: "South Sudan", code: "SS", codeNumber: "+211" },
  { id: 208, name: "Spain", code: "ES", codeNumber: "+34" },
  { id: 209, name: "Sri Lanka", code: "LK", codeNumber: "+94" },
  { id: 210, name: "Sudan", code: "SD", codeNumber: "+249" },
  { id: 211, name: "Suriname", code: "SR", codeNumber: "+597" },
  { id: 211, name: "Svalbard and Jan Mayen", code: "SJ", codeNumber: "+47" },
  { id: 213, name: "Swaziland", code: "SZ", codeNumber: "+268" },
  { id: 214, name: "Sweden", code: "SE", codeNumber: "+46" },
  { id: 215, name: "Switzerland", code: "CH", codeNumber: "+41" },
  { id: 216, name: "Syrian Arab Republic", code: "SY", codeNumber: "+963" },
  { id: 217, name: "Taiwan", code: "TW", codeNumber: "+886" },
  { id: 218, name: "Tajikistan", code: "TJ", codeNumber: "+992" },
  {
    id: 219,
    name: "Tanzania, United Republic of",
    code: "TZ",
    codeNumber: "+255",
  },
  { id: 220, name: "Thailand", code: "TH", codeNumber: "+66" },
  { id: 221, name: "Timor-Leste", code: "TL", codeNumber: "+670" },
  { id: 222, name: "Togo", code: "TG", codeNumber: "+228" },
  { id: 223, name: "Tokelau", code: "TK", codeNumber: "+690" },
  { id: 224, name: "Tonga", code: "TO", codeNumber: "+676" },
  { id: 225, name: "Trinidad and Tobago", code: "TT", codeNumber: "+1" },
  { id: 226, name: "Tunisia", code: "TN", codeNumber: "+216" },
  { id: 227, name: "Turkey", code: "TR", codeNumber: "+90" },
  { id: 228, name: "Turkmenistan", code: "TM", codeNumber: "+993" },
  { id: 229, name: "Turks and Caicos Islands", code: "TC", codeNumber: "+1" },
  { id: 230, name: "Tuvalu", code: "TV", codeNumber: "+688" },
  { id: 231, name: "Uganda", code: "UG", codeNumber: "+256" },
  { id: 232, name: "Ukraine", code: "UA", codeNumber: "+380" },
  { id: 233, name: "United Arab Emirates", code: "AE", codeNumber: "+971" },
  {
    id: 234,
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    codeNumber: "+44",
  },
  { id: 235, name: "United States of America", code: "US", codeNumber: "+1" },
  { id: 236, name: "Uruguay", code: "UY", codeNumber: "+598" },
  { id: 237, name: "Uzbekistan", code: "UZ", codeNumber: "+998" },
  { id: 238, name: "Vanuatu", code: "VU", codeNumber: "+678" },
  {
    id: 239,
    name: "Venezuela (Bolivarian Republic of)",
    code: "VE",
    codeNumber: "+58",
  },
  { id: 240, name: "Viet Nam", code: "VN", codeNumber: "+84" },
  { id: 241, name: "Wallis and Futuna", code: "WF", codeNumber: "+681" },
  { id: 242, name: "Western Sahara", code: "EH", codeNumber: "+212" },
  { id: 243, name: "Yemen", code: "YE", codeNumber: "+967" },
  { id: 244, name: "Zambia", code: "ZM", codeNumber: "+260" },
  { id: 245, name: "Zimbabwe", code: "ZW", codeNumber: "+263" },
];
